### ISSUE TITLE
Homepage on rubygems.org page doesn't work

### ISSUE THREAD

**Issue by dideler** [thuehlinger/daemons#24]
The homepage for the gem on https://rubygems.org/gems/daemons links to http://daemons.rubyforge.org. RubyForge has been down for a while now and doesn't seem to be coming back.

**Comment by jrmhaig** [comment]
Regarding this, is there going to be a version 1.1.10 going up on Ruby Gems? There have been various improvements since 1.1.9.

**Comment by thuehlinger** [comment]
Thanks for pointing out.
I'm working on a new release as we speak.
