### ISSUE TITLE
Unable to find 1.2.0

### ISSUE THREAD

**Issue by jrmhaig** [thuehlinger/daemons#26]
Firstly, thank you for the release of the new version.

However, I only appear to be able to use it with Ruby 2.1.0. With any other version I have tried (2.2.0, 2.2.1 and 1.9.3) I get:

    $ bundle install
    Fetching gem metadata from https://rubygems.org/.........
    Fetching version metadata from https://rubygems.org/..
    Could not find daemons-1.2.0 in any of the sources

and

    $ gem install daemons -v "1.2.0"
    ERROR:  Could not find a valid gem 'daemons' (= 1.2.0) in any repository

I have no problem at all using it with version 2.1.0. Very odd. I don't see anything, either in Github or on Ruby Gems, that specifies the version of Ruby. Does anyone else see this?

**Comment by thuehlinger** [comment]
You're welcome!

For me, daemons 1.2.0 installs correctly:

``` 
ruby -v
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
```

**Comment by ledermann** [comment]
For me, v1.2.0 fails to install on Ruby 2.2.1:

```
~ $ gem install daemons
Fetching: daemons-1.1.9.gem (100%)
Successfully installed daemons-1.1.9
1 gem installed
~ $ gem install daemons -v1.2.0
ERROR:  Could not find a valid gem 'daemons' (= 1.2.0) in any repository
ERROR:  Possible alternatives: daemons
~ $ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
~ $
```

Maybe there is something wrong with the gemspec file...

**Comment by jrmhaig** [comment]
Curiouser and curiouser:

    $ rvm use ruby-2.0.0-p481
    Using /Users/haigj01/.rvm/gems/ruby-2.0.0-p481
    $ gem install daemons -v "1.2.0"
    Successfully installed daemons-1.2.0
    Parsing documentation for daemons-1.2.0
    1 gem installed

    $ rvm use ruby-2.0.0-p598
    Using /Users/haigj01/.rvm/gems/ruby-2.0.0-p598
    $ gem install daemons -v "1.2.0"
    ERROR:  Could not find a valid gem 'daemons' (= 1.2.0) in any repository
    ERROR:  Possible alternatives: daemons

I would imagine that the code of gems on Ruby Gems would be shared across versions as much as possible but perhaps this is not the case and it takes time to proliferate?

**Comment by sodabrew** [comment]
@jrmhaig Each Ruby release includes a version of rubygems, however rubygems has its own release team and release schedule that is quite frequent. `gem --version` will tell you the rubygems version for the current Ruby, which is as important or more important than the version of Ruby itself. If you could post the `gem --version` for each Ruby RVM you have, that will help narrow down the problem.

**Comment by jrmhaig** [comment]
It works with:

| Ruby | Rubygems |
|---|---|
| 2.0.0-p481 | 2.2.2 |
| 2.1.0 | 2.2.2 |

It does not work with:

| Ruby | Rubygems |
|---|---|
| 2.0.0-p598 | 2.4.6 |
| 2.2.0 | 2.4.6 |
| 2.2.1 | 2.4.6 |

I think that that does make it a bit clearer.

**Comment by sodabrew** [comment]
Nice work! Unfortunately I don't see anything obviously suspicious here yet: https://github.com/rubygems/rubygems/blob/master/History.txt

Could you try bisecting the versions between 2.2.2 and 2.4.6 to try and pinpoint the lowest numbered bad version?

**Comment by jrmhaig** [comment]
It works with 2.2.3 but fails with 2.3.0. I see, however, that 2.2.3 isn't in that History.txt file.

**Comment by sunild** [comment]
I was experiencing this problem about an hour ago (Ruby 2.1.5 and Rubygems 2.2.2 as well as after updating to Rubygems 2.4.6). It seems to be fixed now :)

**Comment by thuehlinger** [comment]
I updated my rubygems version from 2.0.4x to 2.4.6, yanked daemons 1.2.0 and released 1.2.1 built by the newer rubygems version. Now it at least installs with 2.4.6. Could everybody test with their respective rubygems version?

**Comment by thuehlinger** [comment]
@jrmhaig @ledermann Can you confirm that daemons 1.2.1 installs correctly for you?

**Comment by ledermann** [comment]
1.2.1 works fine for me - tested with Ruby 2.2.1 and 2.1.5, both using Rubygems 2.4.6. Thanks!

**Comment by jrmhaig** [comment]
Yes, 1.2.1 works for me. Thanks.

**Comment by thuehlinger** [comment]
Great. Thanks!
