### ISSUE TITLE
Test Coverage?

### ISSUE THREAD

**Issue by acuppy** [thuehlinger/daemons#28]
I'm not noticing any RSpec or MiniTest coverage for the gem.  Is that by design or is there another mechanism?  I'm planning to fork it and add assurances (tests) for a project that requires a certain level of coverage to be in place.

If there is not coverage in place, is coverage desired? and if so, is there a preference (RSpec or MiniTest)?

**Comment by sodabrew** [comment]
Unit tests are definitely needed, thank you for offering to begin them! I don't have a testing tool preference. @thuehlinger?

**Comment by acuppy** [comment]
Great.  I'm going to start with RSpec and go from there.

**Comment by thuehlinger** [comment]
I'm happy with either testing tool. Please go on. Thanks in advance!

**Comment by acuppy** [comment]
@sodabrew @thuehlinger Sounds good.  I'll go forth.

**Comment by acuppy** [comment]
If you want to follow progress, check out my fork at https://github.com/acuppy/daemons

**Comment by sodabrew** [comment]
Looks good so far! One comment: I strongly recommend renaming your `master` branch to something descriptive of the project, like `add_unit_tests`, so that if we have other commits on this master branch while you're in progress it won't require any extra merges or messy rebase.

**Comment by acuppy** [comment]
For sure.  I realized that after I started.

On Thursday, March 26, 2015, Aaron Stone <notifications@github.com> wrote:

> Looks good so far! One comment: I strongly recommend renaming your master
> branch to something descriptive of the project, like add_unit_tests, so
> that if we have other commits on this master branch while you're in
> progress it won't require any extra merges or messy rebase.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thuehlinger/daemons/issues/28#issuecomment-86595831>.
>


-- 
*Adam Cuppy*
Partner & COO | Coding ZEAL | Digital Artisans of Web and Mobile
Applications
866.858.5988 x101 | 541.660.3681 | skype: adamcuppy | twitter: @codingzeal

**Comment by acuppy** [comment]
I'm closing this issue in lieu of the PR #32
