### ISSUE TITLE
getting error while accessing some external file

### ISSUE THREAD

**Issue by sunnybogawat** [thuehlinger/daemons#34]
I have created a file called my_server.rb and my_server_crl.rb 

in my_server.rb I have following code
require './src/abcd.rb'

loop do
  p "@@@@@@@@ Welcome to Daemon world @@@@@@@@@@@@@"
  a = ABCD.new
  a.get_status()
  sleep(5)
end

Here When I am trying to require some external file I am getting error.

**Comment by sodabrew** [comment]
Daemons is calling Dir.chdir '/' and so your require is no longer relative to your stating point as you are expecting. Use `require_relative` instead: http://ruby-doc.org/core-1.9.3/Kernel.html#method-i-require_relative
