### ISSUE TITLE
Make daemon start silent

### ISSUE THREAD

**Issue by lmrodriguezr** [thuehlinger/daemons#46]
Hello,

Is there any supported option (or plans to support an option) to tell daemons to run quietly? Usually the `"...: process with pid ... started."` and `"...: trying to stop process with pid..."` messages are very useful, but in some cases (_e.g._ unit testing) it would be great if I could turn them off. It's not a high-priority enhancement, but I would imagine is not very hard to implement.

I use [this trick](http://thinkingdigitally.com/archive/capturing-output-from-puts-in-ruby/) into my tests (for other modules), but combining `fork` and daemons with stdout capturing is not really a good idea. Actually, the unit test jumps to the `ensure` of the method if I do it.

Thanks!
--Miguel.

**Comment by thuehlinger** [comment]
Have you trieded to `:shush` option?

**Comment by lmrodriguezr** [comment]
No, I didn't see it in the docs. How do I pass it? I just tried `:shush=>true` but it doesn't seem to have any effect.

**Comment by thuehlinger** [comment]
The `:shush` option should now work in the latest release (v1.2.4).

**Comment by lmrodriguezr** [comment]
Great! Thanks!
