### ISSUE TITLE
Turns out delayed_job was executing a job causing a segmentation fault, which would kill the delayed_job daemon.

### ISSUE THREAD

**Issue by saju62** [thuehlinger/daemons#68]
I'm getting the following error when i run bin/delayed_job status -
`pid-file for killed process 3045 found (/path_to/tmp/pids/delayed_job.pid), deleting.`

After certain research that I found this error was caused because of segmentation fault.

I found the solution from [stackoverflow](https://stackoverflow.com/questions/11837344/delayed-job-dies-with-out-error-leaving-job-in-locked-state), it says that issue has been resolved. But still, I'm facing the same issue.

**Comment by thuehlinger** [comment]
Looks to me like a problem with delayed_job, please post this issue in the respective place.
